TECH: Add tag variables to modules
smartrent/nerves-hub-terraform pull request #1
Opened 2020-10-06 19:01 UTC by smartryanstewart

Did some formatting as well plus the tags. 

Based on this
[https://smartrent.atlassian.net/jira/software/projects/TECH/boards/5?selectedIssue=TECH-434](url)

TODO:

- [ ] Make sure we have all the things tagged
- [ ] Figure out a testing method.(Another repo...maybe)

2020-10-06 19:01 UTC, smartryanstewart commented
This is not ready for primetime yet. Just wanting to get some thoughts about where we should test this.

2020-10-08 15:41 UTC, rraub commented
lets merge all of our stuff into the `smartrent-main` branch (I just merged in my two PRs with formatting and SSL policy changes into it) So that way all of our diffs wont be mixed up with formatting.

2020-10-08 23:34 UTC, rraub requested changes
Pull in the commits from smartrent-main and hopefully the whitespace diff will go away.

Also we need to actually use these tags variables in the modules.

2020-10-08 23:34 UTC, rraub commented on modules/ecs/cluster/main.tf
>    tags = {
We should use including the the tags variable

2020-10-08 23:34 UTC, rraub commented on modules/rds/main.tf
>    tags = {
should be using the tags variable

2020-10-26 18:22 UTC, rraub requested changes
- Need to add tags to the  aws_lb_target_group's, aws_ssm_parameter's, aws_iam_role's, and aws_ecs_service's (there could be a few others too)
- enable propagate_tags  on aws_ecs_service 
Basically anywhere that we are missing tags we should be adding them.

2020-10-26 20:31 UTC, smartryanstewart commented
> 
> 
>     * Need to add tags to the  aws_lb_target_group's, aws_ssm_parameter's, aws_iam_role's, and aws_ecs_service's (there could be a few others too)
> 
>     * enable propagate_tags  on aws_ecs_service
>       Basically anywhere that we are missing tags we should be adding them.

So everywhere then lol, guess I misunderstood the module part of the ticket, sorry.

2020-10-27 22:35 UTC, rraub approved these changes
Looks great! Thanks! and sorry the ticket wasn't clear 😬

2020-10-28 16:41 UTC, merged